full_name=input('what is your name?  ')
print(full_name)
print('Hello '+full_name)
print(full_name*10)
print(full_name+str('00'))
birth_year=input('Please input your birth year:  ')
age=2020-int(birth_year)
print(age)
print(f'Your age is {age}')
